version: '1'
services:
  calebot:
    build: .
    environment:
      - TOKEN="MTIyMTczNzIzMDI4NTE0NDA5NQ.GeCHy0.T0OLONvsN4H_LfXzMg_PIX3zpEuVFAPdw2WkCg"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
